# Generated by Django 2.1.1 on 2018-09-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_avto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='mileage',
            field=models.BigIntegerField(null=True),
        ),
    ]
