# Generated by Django 2.1.1 on 2018-09-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_avto', '0002_auto_20180922_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='year',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
