# Generated by Django 2.1.1 on 2018-09-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_avto', '0003_ad_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
