# Generated by Django 2.1.1 on 2018-11-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_avto', '0005_auto_20181122_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='desc',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
