# Generated by Django 2.1.1 on 2018-11-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_avto', '0006_ad_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('text', models.TextField(max_length=500, null=True, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('adId', models.ManyToManyField(to='ad_avto.Ad')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
