# Generated by Django 2.1.1 on 2018-11-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_avto', '0008_comments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='isHot',
            field=models.BooleanField(default=0, verbose_name='Вид объявления'),
            preserve_default=False,
        ),
    ]
