# Generated by Django 2.1.1 on 2018-11-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_avto', '0009_ad_ishot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='isHot',
            field=models.BooleanField(verbose_name='Срочное объявление'),
        ),
    ]
